// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.23.4
// source: hello.proto

package hello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HelloWordClient is the client API for HelloWord service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HelloWordClient interface {
	Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
}

type helloWordClient struct {
	cc grpc.ClientConnInterface
}

func NewHelloWordClient(cc grpc.ClientConnInterface) HelloWordClient {
	return &helloWordClient{cc}
}

func (c *helloWordClient) Greet(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := c.cc.Invoke(ctx, "/hello_world.HelloWord/Greet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloWordServer is the server API for HelloWord service.
// All implementations must embed UnimplementedHelloWordServer
// for forward compatibility
type HelloWordServer interface {
	Greet(context.Context, *GreetRequest) (*GreetResponse, error)
	mustEmbedUnimplementedHelloWordServer()
}

// UnimplementedHelloWordServer must be embedded to have forward compatible implementations.
type UnimplementedHelloWordServer struct {
}

func (UnimplementedHelloWordServer) Greet(context.Context, *GreetRequest) (*GreetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Greet not implemented")
}
func (UnimplementedHelloWordServer) mustEmbedUnimplementedHelloWordServer() {}

// UnsafeHelloWordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HelloWordServer will
// result in compilation errors.
type UnsafeHelloWordServer interface {
	mustEmbedUnimplementedHelloWordServer()
}

func RegisterHelloWordServer(s grpc.ServiceRegistrar, srv HelloWordServer) {
	s.RegisterService(&HelloWord_ServiceDesc, srv)
}

func _HelloWord_Greet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloWordServer).Greet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello_world.HelloWord/Greet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloWordServer).Greet(ctx, req.(*GreetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HelloWord_ServiceDesc is the grpc.ServiceDesc for HelloWord service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HelloWord_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hello_world.HelloWord",
	HandlerType: (*HelloWordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greet",
			Handler:    _HelloWord_Greet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}
